### PR TITLE
Fix mixins

### LINKED ISSUE #1: Tips for improving your mixins
The mixin here: [BasinCategoryMixin.java#L38-L66](https://github.com/XiaoHuNao/CreateHeatJS/blob/1.20.1/src/main/java/com/xiaohunao/createheatjs/mixin/BasinCategoryMixin.java#L38-L66) is just a copy of create's existing code with a cancel at the end to early return the method... Instead an injection *later* with only a cancel would mean you do not have to copy a bunch of code which is bad for numerous reasons.

The mixin here: [MixinCategoryMixin.jara#L42-L43](https://github.com/XiaoHuNao/CreateHeatJS/blob/1.20.1/src/main/java/com/xiaohunao/createheatjs/mixin/MixingCategoryMixin.java#L42-L43) also unnesscarily copies code then cancels it (although it is just one line). Just let the existing code run if you don't want to change anything with it! If you need to do two mixins (ie one to do your custom logic and one to skip existing logic) do that instead of one mixin that affects compatibility between two addons trying to modify similar things!
The above also applies to [PackingCategoryMixin.java](https://github.com/XiaoHuNao/CreateHeatJS/blob/1.20.1/src/main/java/com/xiaohunao/createheatjs/mixin/PackingCategoryMixin.java) 

For the mixin here: [ProcessingRecipeJSMixin.java#L9-L15](https://github.com/XiaoHuNao/CreateHeatJS/blob/1.20.1/src/main/java/com/xiaohunao/createheatjs/mixin/ProcessingRecipeJSMixin.java#L9-L15) you should just use the HeatCondition enum as the type of the parameter, and Rhino will handle typewrapping a string input by the scripter to the enum (it also means that autocomplete from addons like ProbeJS will work to suggest strings here!)
It is also a good idea to format the method name in the form `createheatjs$methodname` and use the @RemapPrefixForJS annotation on the class, like KubeJS does here [PlayeKJS.java#L19-L28](https://github.com/KubeJS-Mods/KubeJS/blob/b4ae0ec936b70e4e5e1b26060b368eaa80e3bc7e/common/src/main/java/dev/latvian/mods/kubejs/core/PlayerKJS.java#L19-L28) (ignore the method bodies, that isn't relevent). This tells Rhino to remove the prefix when comparing the method name with the method the scripter is trying to call (so scripters still just called `methodName` despite the name being `createheatjs#methodName` in java). The prefix shows who the method comes from which is helpful in debugging issues and also in cases like minecraft classes it also prevents two mods mixins conflicting if they are named the same, although that isn't very important here. 

For this enum extension code (and the identical stuff in [HeatLevelMixin.java](https://github.com/XiaoHuNao/CreateHeatJS/blob/1.20.1/src/main/java/com/xiaohunao/createheatjs/mixin/HeatLevelMixin.java)): [HeatConditionMixin.java#L29-L45](https://github.com/XiaoHuNao/CreateHeatJS/blob/1.20.1/src/main/java/com/xiaohunao/createheatjs/mixin/HeatConditionMixin.java#L29-L45). You can greatly improve its performance by not making a new array, immuteable list **and** array list for each element in another list. That is incredibly inefficient not only due to reallocating the entire list for each element, but also due to ArrayList's loadFactor system allocating far more than you are ever going to need when you add just a single element more than its original size. You should be able to refactor the code so that you only need 2-3 new lists/arrays in total, rather than that many per element. 
A neat way to go about that is to use ArrayList's addAll method which can be used once they are all constructed into HeatConditions in a seperate list. Or you could manually make a new array by calculating its length by adding the length of the two source arrays, using System.arraycopy to copy the original elements in then adding the new elements to it with a good ol' fashioned for loop.

### PR DESCRIPTION
**Pull request by ChiefArug**
Prefix all mixined methods with createheatjs$
Add MixinExtras to use in the now merged Mixing and Packing category mixins (because the content of the mixin is identical in both we can use the behaviour of targetting multiple classes in one mixin to get both at once!)
Rewrite enum extension code to only allocate a new array once 
Move the inject in BasinCategoryMixin to later so that no code needs to be copied (I'm not sure what the point of this mixin is tho, it just stops some additional JEI Ingredients from being added)
Centralize remap = false in annotations to the main Mixin annotation.
Fixes #1

### CODE REVIEW

**Comment by ChiefArug** [comment]
I have tested this and it works as well as it did before the changes (that is, the ice spikes recipe doesn't seem to work when you actually try it, but the diamond one does and JEI is fine).

If you have any questions about why I made any of the changes, or how one of the mixins works now I'm happy to answer them.

**Comment by XiaoHuNao** [comment]
Wow, these are great

**Comment by XiaoHuNao** [comment]
I have a question to ask you, in Create HeatLevel will be in SEETHING is greater than KINDLED, this judgment is hard-coded to write dead in the enum HeatCondition method testBlazeBurner (), in HeatData in the priority field is to recall to a similar role however, I have not thought of a good solution for the time being. For similar CRYOTHEUM is -1Prior I have not thought of a good solution, so this function has been empty, do you have any good ideas?

**Comment by ChiefArug** [comment]
The way forge does it for its tool tier system is it allows you to insert before/after an existing thing rather than using hardcoded indices. So for here you could have a system where you insert CRYTHEOM before KINDLED, and BLAZE after SEETHING. Implementing this is reasonably easy too, you just loop through until you find the target then add the new thing before/after that. (note that this should be maintained in a separate list as you really shouldn't modify the order of an enum)

**Pull request merged**
